---
root: true
extends:
  - airbnb
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended

env:
  browser: true
  node: true
  es6: true

plugins:
  - import
  - prettier
  - "@typescript-eslint"

parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: "module"

globals:
  __DEV__: true
  __SERVER__: true

rules:
  valid-jsdoc: 2

  object-shorthand: 0
  no-shadow: 0
  class-methods-use-this: 0
  no-console: 0
  no-unresolved: 0
  import/no-unresolved: 0
  no-else-return: 0
  arrow-body-style: 0
  no-new: 0
  no-param-reassign: 0
  consistent-return: 0
  no-return-assign: 0
  no-nested-ternary: 0
  arrow-parens: 0
  global-require: 1
  object-curly-newline: 0
  function-paren-newline: 0
  no-await-in-loop: 1
  no-undef: 0
  no-unused-vars: 0
  no-redeclare: 1
  no-extra-semi: 0
  operator-linebreak: 1

  semi:
  - error
  - never
  - beforeStatementContinuationChars: never
  semi-spacing:
  - error
  - after: true
  before: false
  semi-style:
  - error
  - first
  no-extra-semi: error
  no-unexpected-multiline: error
  no-unreachable: error

  "@typescript-eslint/no-unused-vars": 1
  "@typescript-eslint/no-var-requires": 1
  "@typescript-eslint/camelcase": 1
  "@typescript-eslint/indent": 0
  "@typescript-eslint/no-var-require": 0

  import/no-named-as-default: 0
  import/no-named-as-default-member: 0
  import/extensions: 0
  import/no-extraneous-dependencies: 1
