---
processors:
  - - stylelint-processor-styled-components
    - ignoreFiles:
        - "**/*.scss"

extends:
  - stylelint-config-standard
  - stylelint-config-recommended
  - stylelint-config-styled-components
  - stylelint-config-recess-order

syntax: scss

ignoreFiles:
  - "**/dist/*.scss"

rules:
  selector-pseudo-element-colon-notation: single
  value-list-max-empty-lines: null
  no-duplicate-selectors: null
  rule-empty-line-before: null
  block-no-empty: null
  declaration-empty-line-before: null
  declaration-colon-newline-after: null
  value-list-comma-newline-after: null
  no-descending-specificity: null
  font-family-no-missing-generic-family-keyword: null
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - function
        - if
        - each
        - include
        - mixin
        - for
